# Docker compose to run frontend
version: "3.2"

services:

  frontend:
    image: cloudstateio/cloudstate-proxy-dev-mode:latest
    environment:
      USER_FUNCTION_HOST: frontend-impl
      USER_FUNCTION_PORT: 8080
    depends_on:
      - frontend-impl
    ports:
      - "9003:9000"

  frontend-impl:
    image: ${DOCKER_PUBLISH_TO-cloudstateio}/frontend:dev
    environment:
      SHOPPING_CART_CLIENT_ADDRESS: shopping-cart:9000
      PRODUCT_INVENTORY_CLIENT_ADDRESS: inventory:9000
